export interface ReservationContractInput {
  buyerName: string;
  buyerEmail: string | null;
  buyerPhone: string | null;
  projectName: string;
  developerName: string;
  communityName: string | null;
  unitType: string | null;
  unitNumber: string | null;
  priceAed: number;
  depositAed: number | null;
}

function formatAed(n: number) {
  return `AED ${Math.round(n).toLocaleString()}`;
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// One built-in template for this pass -- no per-developer customization,
// no server-generated PDF (no library installed). This HTML is frozen
// into unit_reservations.contract_snapshot_html at send-time, so what a
// buyer signs can never retroactively change even if the reservation's
// other fields are edited afterward. Print CSS covers "save as PDF" via
// the browser's own print dialog.
export function renderReservationContract(input: ReservationContractInput): string {
  const {
    buyerName,
    buyerEmail,
    buyerPhone,
    projectName,
    developerName,
    communityName,
    unitType,
    unitNumber,
    priceAed,
    depositAed,
  } = input;

  const today = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

  return `
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: Georgia, "Times New Roman", serif; color: #1a1a1a; max-width: 720px; margin: 0 auto; padding: 40px 24px; line-height: 1.6; }
  h1 { font-size: 20px; text-align: center; margin-bottom: 4px; }
  .subtitle { text-align: center; color: #555; font-size: 13px; margin-bottom: 32px; }
  h2 { font-size: 15px; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-top: 28px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; }
  td { padding: 6px 8px; font-size: 14px; vertical-align: top; }
  td.label { color: #555; width: 220px; }
  ol { font-size: 13px; color: #333; padding-left: 20px; }
  ol li { margin-bottom: 8px; }
  .footer { margin-top: 40px; font-size: 12px; color: #777; text-align: center; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <h1>Unit Reservation Agreement</h1>
  <p class="subtitle">${escapeHtml(developerName)} &middot; ${escapeHtml(today)}</p>

  <h2>Parties</h2>
  <table>
    <tr><td class="label">Developer</td><td>${escapeHtml(developerName)}</td></tr>
    <tr><td class="label">Buyer</td><td>${escapeHtml(buyerName)}</td></tr>
    ${buyerEmail ? `<tr><td class="label">Buyer Email</td><td>${escapeHtml(buyerEmail)}</td></tr>` : ""}
    ${buyerPhone ? `<tr><td class="label">Buyer Phone</td><td>${escapeHtml(buyerPhone)}</td></tr>` : ""}
  </table>

  <h2>Property Details</h2>
  <table>
    <tr><td class="label">Project</td><td>${escapeHtml(projectName)}</td></tr>
    ${communityName ? `<tr><td class="label">Community</td><td>${escapeHtml(communityName)}</td></tr>` : ""}
    ${unitType ? `<tr><td class="label">Unit Type</td><td>${escapeHtml(unitType)}</td></tr>` : ""}
    ${unitNumber ? `<tr><td class="label">Unit Number</td><td>${escapeHtml(unitNumber)}</td></tr>` : ""}
    <tr><td class="label">Purchase Price</td><td>${formatAed(priceAed)}</td></tr>
    ${depositAed ? `<tr><td class="label">Reservation Deposit</td><td>${formatAed(depositAed)}</td></tr>` : ""}
  </table>

  <h2>Terms</h2>
  <ol>
    <li>This Reservation Agreement records the Buyer's intent to reserve the unit described above, pending execution of the formal Sale and Purchase Agreement ("SPA") with the Developer.</li>
    <li>The Reservation Deposit stated above secures the unit for the Buyer for a limited period and is applied toward the Purchase Price upon SPA execution, subject to the Developer's standard reservation terms.</li>
    <li>This Agreement does not itself constitute a Sale and Purchase Agreement or transfer of title. Final terms, payment plan, and handover details will be set out in the SPA.</li>
    <li>Prices and unit availability are subject to change until this Agreement is signed by both parties.</li>
  </ol>

  <h2>Signature</h2>
  <p style="font-size: 13px; color: #555;">By signing below, the Buyer confirms they have read and agree to the terms of this Reservation Agreement.</p>

  <div class="footer">Generated by Dubai Property Map — this document was electronically signed.</div>
</body>
</html>`.trim();
}
