-- Broker/Salesperson Referral Program (Sections 1-2: every active Broker
-- and Salesperson automatically gets a unique referral code, e.g.
-- BRK1001 / SP2001).
--
-- Generated by a BEFORE INSERT trigger, not a column default -- a trigger
-- fires no matter which code path creates the row (claim_broker_profile /
-- claim_salesperson_profile self-registration RPCs today, any
-- admin-created-salesperson route, anything added later), so there's no
-- way for a call site to forget to generate one. Codes generate
-- regardless of broker_referral_settings.program_enabled; only *usage* of
-- a code (at registration/checkout) is gated by that flag, so nothing
-- needs a later backfill if the program is toggled off and back on.

alter table brokers
  add column if not exists referral_code text unique,
  add column if not exists referral_code_status text not null default 'active'
    check (referral_code_status in ('active', 'revoked')),
  add column if not exists referral_code_expires_at timestamptz;

alter table salespersons
  add column if not exists referral_code text unique,
  add column if not exists referral_code_status text not null default 'active'
    check (referral_code_status in ('active', 'revoked')),
  add column if not exists referral_code_expires_at timestamptz;

-- brokers has an "owner updates own profile fields" policy (patch_30)
-- that lets a broker update any of their own row's columns except an
-- explicit revoke list -- referral_code and its status/expiry must be on
-- that list, or a broker could rewrite their own code (breaking the
-- sequence-based uniqueness guarantee) or un-revoke it themselves.
-- salespersons has no equivalent self-update policy, so no matching
-- revoke is needed there.
revoke update (referral_code, referral_code_status, referral_code_expires_at) on brokers from authenticated;

create sequence if not exists broker_referral_code_seq start 1001;
create sequence if not exists salesperson_referral_code_seq start 2001;

create or replace function set_broker_referral_code() returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prefix text;
  v_expiry_days int;
begin
  if new.referral_code is null then
    select broker_code_prefix, code_expiry_days into v_prefix, v_expiry_days
      from broker_referral_settings where id = true;
    new.referral_code := coalesce(v_prefix, 'BRK') || nextval('broker_referral_code_seq');
    if v_expiry_days is not null then
      new.referral_code_expires_at := now() + (v_expiry_days || ' days')::interval;
    end if;
  end if;
  return new;
end;
$$;

create trigger brokers_set_referral_code
  before insert on brokers
  for each row execute function set_broker_referral_code();

create or replace function set_salesperson_referral_code() returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prefix text;
  v_expiry_days int;
begin
  if new.referral_code is null then
    select salesperson_code_prefix, code_expiry_days into v_prefix, v_expiry_days
      from broker_referral_settings where id = true;
    new.referral_code := coalesce(v_prefix, 'SP') || nextval('salesperson_referral_code_seq');
    if v_expiry_days is not null then
      new.referral_code_expires_at := now() + (v_expiry_days || ' days')::interval;
    end if;
  end if;
  return new;
end;
$$;

create trigger salespersons_set_referral_code
  before insert on salespersons
  for each row execute function set_salesperson_referral_code();

-- Backfill codes for every broker/salesperson that already exists (the
-- trigger only fires on new inserts) -- reuses the same generator logic
-- inline since triggers don't fire on UPDATE here.
do $$
declare
  v_prefix text;
  v_expiry_days int;
  r record;
begin
  select broker_code_prefix, code_expiry_days into v_prefix, v_expiry_days
    from broker_referral_settings where id = true;
  for r in select id from brokers where referral_code is null loop
    update brokers set
      referral_code = coalesce(v_prefix, 'BRK') || nextval('broker_referral_code_seq'),
      referral_code_expires_at = case when v_expiry_days is not null then now() + (v_expiry_days || ' days')::interval else null end
    where id = r.id;
  end loop;

  select salesperson_code_prefix, code_expiry_days into v_prefix, v_expiry_days
    from broker_referral_settings where id = true;
  for r in select id from salespersons where referral_code is null loop
    update salespersons set
      referral_code = coalesce(v_prefix, 'SP') || nextval('salesperson_referral_code_seq'),
      referral_code_expires_at = case when v_expiry_days is not null then now() + (v_expiry_days || ' days')::interval else null end
    where id = r.id;
  end loop;
end;
$$;

-- Admin revoking a SALESPERSON's code needs no new route -- salespersons
-- has no owner-self-update policy, so its blanket "admin manages all" RLS
-- policy (patch_30) already lets a direct client update of
-- referral_code_status work as-is. A BROKER's code is different: brokers
-- has an owner-self-update policy, so the revoke just above (needed to
-- stop a broker editing their own code) also blocks admin's same-role
-- direct write to it -- revoking a broker's code needs a service-role API
-- route if that admin action is ever built, same as GrantSubscriptionForm
-- needed one for plan_key/subscription_status.

notify pgrst, 'reload schema';
