-- Generated from src/data/mock.ts — run after schema.sql

insert into developers (id, slug, name, initial, color, verified, founded, description, status) values
  (gen_random_uuid(), 'emaar-properties', 'Emaar Properties', 'E', '#22c55e', true, 1997, 'Master developer behind Downtown Dubai, Dubai Marina and Dubai Hills Estate — one of the region''s largest listed real estate companies.', 'active'),
  (gen_random_uuid(), 'damac-properties', 'DAMAC Properties', 'D', '#eab308', true, 2002, 'Luxury developer known for branded residences and golf-front communities across Dubai.', 'active'),
  (gen_random_uuid(), 'sobha-realty', 'Sobha Realty', 'S', '#3b82f6', true, 1976, 'Premium developer focused on craftsmanship, best known for Sobha Hartland along the Dubai Water Canal.', 'active'),
  (gen_random_uuid(), 'nakheel', 'Nakheel', 'N', '#a855f7', true, 2000, 'Creator of Palm Jumeirah and other landmark waterfront master communities.', 'active'),
  (gen_random_uuid(), 'binghatti', 'Binghatti', 'B', '#f97316', true, 2008, 'Fast-growing Dubai developer known for distinctive architecture and rapid off-plan delivery in Business Bay and JVC.', 'active'),
  (gen_random_uuid(), 'ellington-properties', 'Ellington Properties', 'EL', '#14b8a6', true, 2014, 'Design-led boutique developer with a focus on art-inspired residential communities.', 'active');

insert into communities (id, slug, name, description, lng, lat, x_pct, y_pct, pin_color) values
  (gen_random_uuid(), 'palm-jumeirah', 'Palm Jumeirah', 'Iconic man-made island with beachfront villas and branded residences.', 55.1385, 25.1124, 9, 30, '#3b82f6'),
  (gen_random_uuid(), 'dubai-marina', 'Dubai Marina', 'High-rise waterfront living with a bustling promenade and marina walk.', 55.14, 25.0805, 21, 36, '#eab308'),
  (gen_random_uuid(), 'jumeirah-lakes-towers', 'Jumeirah Lakes Towers', 'Mixed-use lake-front towers close to Dubai Marina and JBR.', 55.142, 25.0693, 25, 46, '#22c55e'),
  (gen_random_uuid(), 'jumeirah-village-circle', 'Jumeirah Village Circle', 'Family-friendly circular community with parks and affordable apartments.', 55.208, 25.0596, 17, 58, '#f97316'),
  (gen_random_uuid(), 'motor-city', 'Motor City', 'Motorsport-themed community with low-rise apartments and townhouses.', 55.24, 25.047, 23, 68, '#3b82f6'),
  (gen_random_uuid(), 'dubai-south', 'Dubai South', 'Airport-district master plan anchored by Al Maktoum International and Expo City.', 55.17, 24.897, 13, 82, '#a855f7'),
  (gen_random_uuid(), 'business-bay', 'Business Bay', 'Dubai''s business and lifestyle hub along the Dubai Water Canal.', 55.2708, 25.1857, 45, 37, '#22c55e'),
  (gen_random_uuid(), 'downtown-dubai', 'Downtown Dubai', 'Home to Burj Khalifa, Dubai Mall and Dubai Fountain — the city''s premium core.', 55.2744, 25.1972, 53, 27, '#ef4444'),
  (gen_random_uuid(), 'dubai-creek-harbour', 'Dubai Creek Harbour', 'Waterfront master plan facing Ras Al Khor, future home of Dubai Creek Tower.', 55.3467, 25.195, 69, 13, '#3b82f6'),
  (gen_random_uuid(), 'arjan', 'Arjan', 'Emerging affordable community near Dubai Miracle Garden.', 55.246, 25.063, 47, 58, '#eab308'),
  (gen_random_uuid(), 'damac-hills', 'DAMAC Hills', 'Golf-course community with villas, townhouses and Trump International Golf Club.', 55.253, 25.029, 60, 58, '#22c55e'),
  (gen_random_uuid(), 'damac-hills-2', 'DAMAC Hills 2', 'Affordable family villas and townhouses further along Al Qudra Road.', 55.22, 24.995, 67, 67, '#a855f7'),
  (gen_random_uuid(), 'dubai-hills-estate', 'Dubai Hills Estate', 'Green master community with Dubai Hills Mall and championship golf course.', 55.247, 25.105, 74, 37, '#f97316'),
  (gen_random_uuid(), 'meydan', 'Meydan', 'Home to Meydan Racecourse, canal-front villas and new golf residences.', 55.305, 25.156, 79, 52, '#3b82f6');

-- Projects reference developers/communities by slug via subselects
insert into projects (id, slug, name, developer_id, community_id, property_type, listing_type, status, approval_status, featured, price_from_aed, payment_plan, bedrooms_from, bedrooms_to, unit_types, handover_quarter, handover_year, rating, reviews, gradient, tags, description, amenities, views) values
  (gen_random_uuid(), 'chelsea-residences', 'Chelsea Residences', (select id from developers where slug = 'damac-properties'), (select id from communities where slug = 'downtown-dubai'), 'Apartments', 'off-plan', 'featured', 'approved', true, 1200000, '70/30', 1, 4, ARRAY['1BR','2BR','3BR','4BR']::text[], 'Q2', 2028, 4.8, 128, 'from-amber-500/40 via-slate-800 to-slate-950', ARRAY['new-launch','waterfront']::text[], 'Waterfront residences in the heart of Downtown Dubai with resort-style amenities and skyline views.', ARRAY['Pool','Gym','Kids Area','Cinema','Sky Lounge','Smart Home']::text[], 2842),
  (gen_random_uuid(), 'sobha-hartland-ii', 'Sobha Hartland II', (select id from developers where slug = 'sobha-realty'), (select id from communities where slug = 'business-bay'), 'Apartments', 'off-plan', 'published', 'approved', false, 1600000, '60/40', 1, 4, ARRAY['1BR','2BR','3BR','4BR']::text[], 'Q4', 2027, 4.7, 96, 'from-sky-500/40 via-slate-800 to-slate-950', ARRAY['luxury','waterfront']::text[], 'A lush waterfront extension of Sobha Hartland with lagoon views and premium finishes.', ARRAY['Pool','Gym','Beach','Parking','Pet Friendly']::text[], 2317),
  (gen_random_uuid(), 'binghatti-skyrise', 'Binghatti Skyrise', (select id from developers where slug = 'binghatti'), (select id from communities where slug = 'business-bay'), 'Apartments', 'off-plan', 'published', 'approved', false, 1100000, '50/50', 0, 3, ARRAY['Studio','1BR','2BR','3BR']::text[], 'Q1', 2027, 4.5, 74, 'from-emerald-500/40 via-slate-800 to-slate-950', ARRAY['new-launch','high-roi']::text[], 'Bold architectural tower in Business Bay with striking facades and canal views.', ARRAY['Pool','Gym','Sky Lounge','Parking']::text[], 1942),
  (gen_random_uuid(), 'bay-by-cavalli', 'Bay by Cavalli', (select id from developers where slug = 'damac-properties'), (select id from communities where slug = 'dubai-creek-harbour'), 'Apartments', 'off-plan', 'published', 'approved', false, 2900000, '70/30', 2, 5, ARRAY['2BR','3BR','4BR','5BR']::text[], 'Q4', 2028, 4.8, 61, 'from-fuchsia-500/40 via-slate-800 to-slate-950', ARRAY['luxury','waterfront','high-roi']::text[], 'Roberto Cavalli-branded waterfront residences overlooking Dubai Creek Harbour.', ARRAY['Pool','Gym','Beach','Cinema','Smart Home']::text[], 1781),
  (gen_random_uuid(), 'ellington-house-iv', 'Ellington House IV', (select id from developers where slug = 'ellington-properties'), (select id from communities where slug = 'dubai-hills-estate'), 'Apartments', 'off-plan', 'published', 'approved', false, 1800000, '60/40', 1, 4, ARRAY['1BR','2BR','3BR','4BR']::text[], 'Q2', 2027, 4.6, 52, 'from-rose-500/40 via-slate-800 to-slate-950', ARRAY['luxury']::text[], 'Art-inspired residences in Dubai Hills Estate with golf course views.', ARRAY['Pool','Gym','Kids Area','Parking']::text[], 1512),
  (gen_random_uuid(), 'palm-beach-towers', 'Palm Beach Towers', (select id from developers where slug = 'nakheel'), (select id from communities where slug = 'palm-jumeirah'), 'Apartments', 'ready', 'published', 'approved', false, 3800000, '100% on handover', 1, 3, ARRAY['1BR','2BR','3BR']::text[], 'Q1', 2026, 4.9, 210, 'from-indigo-500/40 via-slate-800 to-slate-950', ARRAY['luxury','waterfront']::text[], 'Beachfront towers on Palm Jumeirah''s crescent with private beach access.', ARRAY['Beach','Pool','Gym','Smart Home','Parking']::text[], 3120),
  (gen_random_uuid(), 'marina-vista', 'Marina Vista', (select id from developers where slug = 'emaar-properties'), (select id from communities where slug = 'dubai-marina'), 'Apartments', 'ready', 'published', 'approved', false, 1450000, '100% on handover', 1, 3, ARRAY['1BR','2BR','3BR']::text[], 'Q3', 2025, 4.6, 143, 'from-amber-500/40 via-slate-800 to-slate-950', ARRAY['waterfront']::text[], 'Marina-facing apartments minutes from JBR Beach and the tram.', ARRAY['Pool','Gym','Parking','Kids Area']::text[], 1988),
  (gen_random_uuid(), 'jlt-city-towers', 'JLT City Towers', (select id from developers where slug = 'binghatti'), (select id from communities where slug = 'jumeirah-lakes-towers'), 'Apartments', 'rent', 'published', 'approved', false, 65000, '1 cheque', 0, 2, ARRAY['Studio','1BR','2BR']::text[], 'Ready', 2024, 4.3, 88, 'from-emerald-500/40 via-slate-800 to-slate-950', ARRAY['under-1m']::text[], 'Well-connected lake-view towers with easy access to JBR and Marina.', ARRAY['Pool','Gym','Parking']::text[], 1244),
  (gen_random_uuid(), 'circle-mansions', 'Circle Mansions', (select id from developers where slug = 'ellington-properties'), (select id from communities where slug = 'jumeirah-village-circle'), 'Villas', 'off-plan', 'published', 'approved', false, 980000, '80/20', 1, 3, ARRAY['1BR','2BR','3BR']::text[], 'Q3', 2026, 4.4, 41, 'from-sky-500/40 via-slate-800 to-slate-950', ARRAY['under-1m','high-roi']::text[], 'Contemporary low-rise residences around JVC''s central park.', ARRAY['Pool','Gym','Kids Area']::text[], 1032),
  (gen_random_uuid(), 'damac-lagoons-venice', 'DAMAC Lagoons – Venice', (select id from developers where slug = 'damac-properties'), (select id from communities where slug = 'damac-hills-2'), 'Villas', 'off-plan', 'published', 'approved', false, 1450000, '70/30', 3, 6, ARRAY['3BR','4BR','5BR','6BR']::text[], 'Q2', 2027, 4.5, 67, 'from-fuchsia-500/40 via-slate-800 to-slate-950', ARRAY['villas','waterfront']::text[], 'Venice-themed lagoon villas with crystal lagoons and white-sand beaches.', ARRAY['Beach','Pool','Golf','Parking','Pet Friendly']::text[], 1670),
  (gen_random_uuid(), 'trump-estates', 'Trump Estates', (select id from developers where slug = 'damac-properties'), (select id from communities where slug = 'damac-hills'), 'Villas', 'ready', 'published', 'approved', false, 4200000, '100% on handover', 4, 7, ARRAY['4BR','5BR','6BR','7BR']::text[], 'Ready', 2024, 4.7, 39, 'from-rose-500/40 via-slate-800 to-slate-950', ARRAY['luxury','villas']::text[], 'Golf-front luxury villas at DAMAC Hills bordering the Trump International Golf Club.', ARRAY['Golf','Pool','Smart Home','Parking']::text[], 1420),
  (gen_random_uuid(), 'creek-rise-towers', 'Creek Rise Towers', (select id from developers where slug = 'emaar-properties'), (select id from communities where slug = 'dubai-creek-harbour'), 'Apartments', 'off-plan', 'published', 'pending', false, 1350000, '80/20', 1, 3, ARRAY['1BR','2BR','3BR']::text[], 'Q1', 2029, 4.6, 12, 'from-indigo-500/40 via-slate-800 to-slate-950', ARRAY['new-launch','waterfront','high-roi']::text[], 'New launch overlooking the Ras Al Khor wildlife sanctuary and Downtown skyline.', ARRAY['Pool','Gym','Cinema']::text[], 612),
  (gen_random_uuid(), 'hills-park-villas', 'Hills Park Villas', (select id from developers where slug = 'emaar-properties'), (select id from communities where slug = 'dubai-hills-estate'), 'Villas', 'off-plan', 'published', 'review', false, 3600000, '60/40', 4, 6, ARRAY['4BR','5BR','6BR']::text[], 'Q4', 2027, 4.7, 8, 'from-amber-500/40 via-slate-800 to-slate-950', ARRAY['luxury','villas']::text[], 'Contemporary family villas facing Dubai Hills Golf Course.', ARRAY['Golf','Pool','Gym','Parking']::text[], 540),
  (gen_random_uuid(), 'meydan-canal-villas', 'Meydan Canal Villas', (select id from developers where slug = 'sobha-realty'), (select id from communities where slug = 'meydan'), 'Villas', 'off-plan', 'draft', 'pending', false, 5200000, '70/30', 5, 7, ARRAY['5BR','6BR','7BR']::text[], 'Q2', 2028, 0, 0, 'from-sky-500/40 via-slate-800 to-slate-950', ARRAY['luxury','waterfront']::text[], 'Canal-front villas in Meydan with private docks and skyline views.', ARRAY['Pool','Smart Home','Parking']::text[], 210),
  (gen_random_uuid(), 'arjan-green-residence', 'Arjan Green Residence', (select id from developers where slug = 'binghatti'), (select id from communities where slug = 'arjan'), 'Apartments', 'off-plan', 'published', 'approved', false, 720000, '1/60', 0, 2, ARRAY['Studio','1BR','2BR']::text[], 'Q3', 2026, 4.2, 34, 'from-emerald-500/40 via-slate-800 to-slate-950', ARRAY['under-1m','high-roi']::text[], 'Affordable apartments moments from Dubai Miracle Garden.', ARRAY['Pool','Gym']::text[], 980);

insert into leads (id, project_id, name, phone, email, country, budget_aed, status, source, assigned_agent, notes) values
  (gen_random_uuid(), (select id from projects where slug = 'chelsea-residences'), 'James Whitfield', '+44 7911 123456', 'james.w@example.com', 'United Kingdom', 1500000, 'new', 'Website', 'Fatima Al Marri', 'Interested in 2BR, prefers Q4 2027 handover.'),
  (gen_random_uuid(), (select id from projects where slug = 'sobha-hartland-ii'), 'Elena Petrova', '+7 916 234 5678', 'elena.p@example.com', 'Russia', 2200000, 'contacted', 'WhatsApp', 'Omar Sharif', 'Wants payment plan details sent via email.'),
  (gen_random_uuid(), (select id from projects where slug = 'bay-by-cavalli'), 'Wei Zhang', '+86 138 0013 8000', 'wei.zhang@example.com', 'China', 3000000, 'qualified', 'Property Finder', 'Fatima Al Marri', 'Viewing scheduled next week.'),
  (gen_random_uuid(), (select id from projects where slug = 'circle-mansions'), 'Ahmed Hassan', '+20 100 123 4567', 'ahmed.h@example.com', 'Egypt', 900000, 'new', 'Instagram Ads', 'Layla Haddad', 'First-time investor, needs mortgage guidance.'),
  (gen_random_uuid(), (select id from projects where slug = 'marina-vista'), 'Sara Müller', '+49 151 23456789', 'sara.m@example.com', 'Germany', 1750000, 'won', 'Referral', 'Omar Sharif', 'Booking confirmed, 10% paid.'),
  (gen_random_uuid(), (select id from projects where slug = 'binghatti-skyrise'), 'Rohan Mehta', '+91 98765 43210', 'rohan.m@example.com', 'India', 1200000, 'contacted', 'Website', 'Layla Haddad', 'Comparing with 2 other Business Bay projects.'),
  (gen_random_uuid(), (select id from projects where slug = 'palm-beach-towers'), 'Fatima Al Suwaidi', '+971 50 123 4567', 'fatima.s@example.com', 'UAE', 4500000, 'qualified', 'Walk-in', 'Fatima Al Marri', 'Cash buyer, wants sea-facing unit.'),
  (gen_random_uuid(), (select id from projects where slug = 'damac-lagoons-venice'), 'Michael Chen', '+1 415 555 0192', 'michael.c@example.com', 'USA', 1450000, 'lost', 'Property Finder', 'Omar Sharif', 'Went with a competitor development.'),
  (gen_random_uuid(), (select id from projects where slug = 'arjan-green-residence'), 'Nadia Rahman', '+880 1712 345678', 'nadia.r@example.com', 'Bangladesh', 780000, 'new', 'Facebook Ads', 'Layla Haddad', 'Budget conscious, wants studio.'),
  (gen_random_uuid(), (select id from projects where slug = 'bay-by-cavalli'), 'Luca Romano', '+39 320 1234567', 'luca.r@example.com', 'Italy', 2900000, 'contacted', 'Referral', 'Fatima Al Marri', 'Interested in Cavalli-branded interiors.');

insert into bookings (id, project_id, client_name, scheduled_date, scheduled_time, agent, status) values
  (gen_random_uuid(), (select id from projects where slug = 'chelsea-residences'), 'James Whitfield', '2026-07-24', '11:00 AM', 'Fatima Al Marri', 'confirmed'),
  (gen_random_uuid(), (select id from projects where slug = 'bay-by-cavalli'), 'Wei Zhang', '2026-07-25', '2:30 PM', 'Fatima Al Marri', 'confirmed'),
  (gen_random_uuid(), (select id from projects where slug = 'marina-vista'), 'Sara Müller', '2026-07-20', '10:00 AM', 'Omar Sharif', 'completed'),
  (gen_random_uuid(), (select id from projects where slug = 'palm-beach-towers'), 'Fatima Al Suwaidi', '2026-07-26', '4:00 PM', 'Fatima Al Marri', 'confirmed'),
  (gen_random_uuid(), (select id from projects where slug = 'damac-lagoons-venice'), 'Michael Chen', '2026-07-17', '1:00 PM', 'Omar Sharif', 'cancelled'),
  (gen_random_uuid(), (select id from projects where slug = 'binghatti-skyrise'), 'Rohan Mehta', '2026-07-27', '5:30 PM', 'Layla Haddad', 'confirmed'),
  (gen_random_uuid(), (select id from projects where slug = 'sobha-hartland-ii'), 'Elena Petrova', '2026-07-15', '12:00 PM', 'Omar Sharif', 'completed');

